[pyprland]
plugins = [
    "magnify",
    "scratchpads",
]

[scratchpads.dropdown]
animation = "fromTop"
command = "alacritty --class scratchpad"
margin-top = 130

[scratchpads.nemo]
animation = "fromTop"
command="nemo --class nemo"
class = "nemo"
class_match= "true"
lazy = true
margin-top = 130