# Shell variables
# Generated by 'wal'
wallpaper='/home/kleidis/Downloads/pexels-james-wheeler-1519088.jpg'

# Special
background='#021633'
foreground='#b1b8c2'
cursor='#b1b8c2'

# Colors
color0='#021633'
color1='#5F5659'
color2='#9E6149'
color3='#C19D5C'
color4='#07498B'
color5='#2C538A'
color6='#305489'
color7='#b1b8c2'
color8='#7b8087'
color9='#5F5659'
color10='#9E6149'
color11='#C19D5C'
color12='#07498B'
color13='#2C538A'
color14='#305489'
color15='#b1b8c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
