--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kleidis/Downloads/pexels-james-wheeler-1519088.jpg"

-- Special
background="#021633"
foreground="#b1b8c2"
cursor="#b1b8c2"

-- Colors
color0="#021633"
color1="#5F5659"
color2="#9E6149"
color3="#C19D5C"
color4="#07498B"
color5="#2C538A"
color6="#305489"
color7="#b1b8c2"
color8="#7b8087"
color9="#5F5659"
color10="#9E6149"
color11="#C19D5C"
color12="#07498B"
color13="#2C538A"
color14="#305489"
color15="#b1b8c2"
