--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kleidis/Wallpapers/wallhaven-zyvg1j.png"

-- Special
background="#0d1236"
foreground="#efd7d5"
cursor="#efd7d5"

-- Colors
color0="#0d1236"
color1="#4E69C6"
color2="#B761B5"
color3="#1C9FDA"
color4="#328BCE"
color5="#4987CF"
color6="#FBB6BD"
color7="#efd7d5"
color8="#a79695"
color9="#4E69C6"
color10="#B761B5"
color11="#1C9FDA"
color12="#328BCE"
color13="#4987CF"
color14="#FBB6BD"
color15="#efd7d5"
