# Shell variables
# Generated by 'wal'
wallpaper="/home/kleidis/Wallpapers/wallhaven-zyvg1j.png"

# Special
background='#040612'
foreground='#c0c0c3'
cursor='#c0c0c3'

# Colors
color0='#040612'
color1='#4E69C6'
color2='#B761B5'
color3='#1C9FDA'
color4='#328BCE'
color5='#4987CF'
color6='#FBB6BD'
color7='#c0c0c3'
color8='#42444d'
color9='#4E69C6'
color10='#B761B5'
color11='#1C9FDA'
color12='#328BCE'
color13='#4987CF'
color14='#FBB6BD'
color15='#c0c0c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
